# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-04 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0005_financialoperation_alreadypayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialoperation',
            name='company',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialoperation',
            name='fileLink',
            field=models.FileField(upload_to=b'documents/%Y/%m/%d'),
        ),
    ]
