# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-05 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0006_auto_20181204_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialoperation',
            name='fileLink',
            field=models.FileField(blank=True, upload_to=b'documents/%Y/%m/%d'),
        ),
    ]
