# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0007_auto_20181205_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialoperation',
            name='positionNumber',
            field=models.TextField(max_length=50),
        ),
    ]
